### PR TITLE
Fixes app name

### PR DESCRIPTION
**Pull request by nkakouros**

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
Sorry, this is called `keydgen` on purpose, but thank you for the PR.

**Comment by nkakouros** [comment]
I understand the naming os `ssh-keydgen`, but in the code there are places where you call the app `ssh-keygen` instead of `ssh-keydgen. Is this on purpose?

**Comment by cornfeedhobo** [comment]
@tterranigma My sincere apologies. I see what you mean. My first pass glance at this PR saw it as the inverse of your suggestion. Indeed this would be nice to fix. Unfortunately I am archiving this repo most likely. I was naive and wrote this too tightly coupled to Go's implementation of key generation, making the keys non-deterministic in later versions. I'm currently researching the SSH key generation process to see if I can roll a better implementation of this which I will validate with a python library that does the same.

**Comment by nkakouros** [comment]
I wish you the best of luck as this project has been really useful so far!

**Pull request closed without merging**
